### ISSUE TITLE
Kick feature for everyone

### ISSUE THREAD

**Issue by gridhead** [astrosonic/sanctuary#23]

**Comment by MohitThorat** [comment]
Should this feature be only available to the one who created or for everyone?

**Comment by gridhead** [comment]
For everyone. This chatroom is transient and is expected to be used in highly sensitive situations where even a spammer can take over the creator and start typing trash.

**Comment by tripathyprateek** [comment]
Hey @t0xic0der I am having a  little bit of experience in socket.io. I might implement this feature, but I cannot provide a timeframe when I will be able to implement this as I am new to Socket.io

**Comment by gridhead** [comment]
Don't worry. @tripathyprateek  Take your time into studying it and implementing it. Should I assign this issue to you?

P.S. Although there are no strict "timeframes" per se, I might need to reassign this issue to somebody else if they happen to express their interest on this issue before you finish implementing it,

**Comment by tripathyprateek** [comment]
Dont assign it to me right now. I will get it implemented and put a PR.

**Comment by gridhead** [comment]
Unfortunately that is not how it works @tripathyprateek. If you are working on this issue, it should be assigned to you. In this way, contributors would get to know that this issue is being worked on by you and hence, they can pick some other issue to work on.

**Comment by tripathyprateek** [comment]
Okay sure. Assign it to me then.

**Comment by gridhead** [comment]
Cool. The issue has been assigned to you. :slightly_smiling_face:

**Comment by gridhead** [comment]
Implemented with the latest PR #39
