### ISSUE TITLE
Leaving a chatroom also sends an empty message to chat

### ISSUE THREAD

**Issue by VaibhavSaini19** [astrosonic/sanctuary#33]

**Comment by MohitThorat** [comment]
I couldn't verify this issue. Can you give more details?

**Comment by gridhead** [comment]
Steps to recreate the issue.
- Create a chatroom from one browser session and join the chatroom with the same browser session.
- Copy the chatroom ID and join the chatroom from another browser session with another username.
- Make some conversation happen - these will simply act as placeholders.
- Leave the chatroom being one of the joined users from one of the browser sessions.
- You will see an empty message has been sent to the remaining participants.

**Comment by gridhead** [comment]
This issue has been rendered invalid due to the redesign.
