### ISSUE TITLE
Add Option for IP Address

### ISSUE THREAD

**Issue by ghost** [astrosonic/sanctuary#59]
I have seen that this project does not allow to choose IP Address for hosting the Web Application, so i thought I can fix it.
Hence I will be getting a new pull request Up for the same.

**Comment by gridhead** [comment]
Thank you for marking that out. @xcodz-dot.

The community usually goes into replicating the defect/bug that is listed, then ideates the way of solving it and finally moves on to developing a fix to address the said issue. You are requested to discuss in detail under this ticket how such a feature addition can be important and why it should be incorporated.

**Comment by ghost** [comment]
well, when you host a server, you need to host on a static IP address which can be accessed by a DNS Server. Also you might want to host the server on local LAN connection so you might want to put on a custom IP Address for the server to host. So i suggest we can simply add an argument to click and pass the address to run method of flask application

**Comment by ghost** [comment]
Please assign this to me

**Comment by gridhead** [comment]
This needs some thorough discussions. I'd ask @VaibhavSaini19 @s-katte @shivangswain @tripathyprateek to explore this and get into discussion.

**Comment by s-katte** [comment]
> well, when you host a server, you need to host on a static IP address which can be accessed by a DNS Server. Also you might want to host the server on local LAN connection so you might want to put on a custom IP Address for the server to host. So i suggest we can simply add an argument to click and pass the address to run method of flask application

As I understand, you are suggesting that instead of default ```localhost:PORT``` only, we can have and option that user can provide input for IP as well, like suppose ```198.6.6.1:PORT``` ?
Please correct me if i am wrong @xcodz-dot

**Comment by ghost** [comment]
Yes, by default we will keep it localhost but if user specifies the option we will keep the user one. This would not break compatibility but only add a optional command line option. Also we will take input in this format `192.168.43.1` and not `192.168.43.1:PORT`

**Comment by shivangswain** [comment]
This is a good feature to have in my opinion and I don't see any problem with merging only this change from the linked PR. I'd suggest @xcodz-dot drop the other additions they have made to the PR and only let this functionality be added to the project for now. (see: Atomic PRs)

**Comment by ghost** [comment]
i did not quite understand, what i am thinking is:
* let my previous PR be done (#70)
* i will get myself assigned to this
* the next day i will submit PR for this

**Comment by ghost** [comment]
please assign this to me :smile:

**Comment by tripathyprateek** [comment]
> please assign this to me 😄

@t0xic0der please assign

**Comment by ghost** [comment]
> This is a good feature to have in my opinion and I don't see any problem with merging only this change from the linked PR. I'd suggest @xcodz-dot drop the other additions they have made to the PR and only let this functionality be added to the project for now. (see: Atomic PRs)

I just understood it now, but i think i will startup clean with a new PR

**Comment by ghost** [comment]
@t0xic0der please assign this to me :smile:

**Comment by shivangswain** [comment]
I apologize for the delay in assigning; you may start contributing now.

**Comment by ghost** [comment]
thanks! 😄

**Comment by gridhead** [comment]
Hi @xcodz-dot,

I know it has been a long while since we last attended your issues/PRs and I understand that it can be disheartening to be in such a situation. We would definitely get back to working on this at a later date, whenever we would find some time out of the tasks we are usually engaged in. Thanks for contributing. :)

**Comment by ghost** [comment]
:)
