### ISSUE TITLE
Servers can be unified using threading

### ISSUE THREAD

**Issue by ghost** [astrosonic/sanctuary#65]
I am looking forward to this issue, I will also initiate a seperate pull request for this one

**Comment by gridhead** [comment]
> There are unnecessarily two server files which can be easily threaded into single one.

You are requested to kindly focus on the functionality that can be introduced over criticizing what exists for the issue topic. It is certainly not a bug but more of redundancy here, A suitable title maybe "Servers can be unified using threading" etc.

> I am looking forward to this issue, I will also initiate a separate pull request for this one

Cool. I am assigning you this issue.

**Comment by ghost** [comment]
Sorry for being late, I will start the work now

**Comment by ghost** [comment]
easy
