### ISSUE TITLE
Empty messages can be sent using repeated spaces

### ISSUE THREAD

**Issue by gridhead** [astrosonic/sanctuary#69]
Although an empty string is not taken into account but still repeated spaces are considered to be sent. This should not happen.

![image](https://user-images.githubusercontent.com/49605954/100829840-53bca280-3488-11eb-9b27-b4c1f8a45388.png)

**Comment by RMaster121** [comment]
@t0xic0der I would like to work on this issue.

**Comment by gridhead** [comment]
Sure @RMaster121. I'm assigning this issue to you

**Comment by ghost** [comment]
@t0xic0der i think we can close this cause the PR with its fix is merged

**Comment by gridhead** [comment]
Closed via #71. Thanks for marking this one out.

**Comment by ghost** [comment]
Please check the issue status its still open
